export const LANDING = '/'
export const MAIN = '/main'
export const CREATEACCOUNT = '/create-account'
export const PROFILE = '/profile'
export const EDITPROFILE = '/profile#edit'
export const PASTDOCUMENTS = '/profile#past-documents'
